/// Flutter icons TwitterIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  TwitterIcons
///      fonts:
///       - asset: fonts/TwitterIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class TwitterIcons {
  TwitterIcons._();

  static const _kFontFam = 'TwitterIcons';
  static const String? _kFontPkg = null;

  static const IconData bell = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comment = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dms = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData like = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData newtweet = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData retweet = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData verified = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
